# Generated by Django 3.2.8 on 2024-06-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='desired_job',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='education_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='expected_salary',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='graduation_school',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='graduation_year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='job_status',
            field=models.CharField(blank=True, choices=[('seeking', '求职中'), ('employed', '在职')], max_length=20),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='residence',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='work_location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
