# Generated by Django 3.2.8 on 2024-06-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0002_auto_20240613_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='resume',
            field=models.URLField(blank=True, max_length=256),
        ),
    ]
