# Generated by Django 3.2.8 on 2024-06-18 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobseeker', '0003_jobseeker_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.URLField(blank=True, max_length=256)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('residence', models.CharField(blank=True, max_length=255)),
                ('graduation_school', models.CharField(blank=True, max_length=255)),
                ('desired_job', models.CharField(blank=True, max_length=255)),
                ('expected_salary', models.CharField(blank=True, max_length=50)),
                ('work_location', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('resume', models.URLField(blank=True, max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
