# Generated by Django 3.2.8 on 2024-06-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0005_form_jobpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='photo',
            field=models.URLField(blank=True, default='https://tse1-mm.cn.bing.net/th/id/OIP-C.-BD7wuSAaquBdulv7uAHjgHaHa?rs=1&pid=ImgDetMain', max_length=256),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='photo',
            field=models.URLField(blank=True, default='https://tse1-mm.cn.bing.net/th/id/OIP-C.-BD7wuSAaquBdulv7uAHjgHaHa?rs=1&pid=ImgDetMain', max_length=256),
        ),
        migrations.DeleteModel(
            name='Form',
        ),
        migrations.DeleteModel(
            name='JobPost',
        ),
    ]
