# Generated by Django 3.2.8 on 2024-06-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0007_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='job_position',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
